// Main actions file

//export const API = 'https://rekall-server.herokuapp.com';

export const ActionTypes = {
  FETCH_PROFILE_INFO: 'FETCH_PROFILE_INFO',
  CREATE_USER: 'CREATE_USER',
  LOGIN: 'LOGIN',
  ADD_USER_ALBUM: 'ADD_USER_ALBUM',
  ADD_SHARED_ALBUM: 'ADD_SHARED_ALBUM',
  FRIEND_SHENANIGANS: 'FRIEND_SHENANIGANS',
  NEW_PROFILE_PIC: 'NEW_PROFILE_PIC',
  GET_ALBUMS: 'GET_ALBUMS',
  GET_SHARED_ALBUMS: 'GET_SHARED_ALBUMS'
}